### ISSUE TITLE
this.chart.destroyChart is not a function getting this error. whenever i tried it.

### ISSUE THREAD

**Issue by muntakim1** [Saigesp/vue-d3-charts#16]
An error occured while showing the error page
Unfortunately an error occured and while showing the error page another error occured

Error details: TypeError: this.chart.destroyChart is not a function

**Comment by hoopyfrood** [comment]
This occurs when data hasn't loaded yet. Make sure you fetch your data as early as possible in the lifecycle, ended up using "asyncData" in nuxt to make it work.

**Comment by Saigesp** [comment]
Hi @muntakim1, thanks for the report, and sorry for my late response.

I haven't tried this library with Nuxt, but as @hoopyfrood said (thanks you so much!), it's probably because the data isn't loaded yet.
