### ISSUE TITLE
The word cloud chart does not show Persian and Arabic texts.

### ISSUE THREAD

**Issue by farshidrezaei** [Saigesp/vue-d3-charts#24]
The word cloud chart does not show Persian and Arabic texts.
my data :

```js
data= [
   {
      size:265919
      word:"ایران"
   },
   {
      size:263271
      word:"قران"
   },
   {
      size:259770
      word:"اسلام"
   }
];
```

but chart show blank box.

**Comment by Saigesp** [comment]
Hi @farshidrezaei, sorry for the delay.

The wordscloud is a wrapper for https://github.com/jasondavies/d3-cloud, so I suspect that the error is generated in it. Please try using it directly
