### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tcurdt** [Saigesp/vue-d3-charts#28]
Any chance for a different or a dual license?

The GPL is tainting and therefor a big headache on the legal side. It may severely limit who can use it like this.

https://stackoverflow.com/questions/1239470/restrictions-of-gpl-on-javascript-libraries

**Comment by Saigesp** [comment]
Hi!

I am not an expert in licensing, but at the moment I prefer to keep the GPL. However, I am open to exceptions. What is your issue with the GPL?

**Comment by tcurdt** [comment]
The GPL is tainting. Quoting from wikipedia "The GPL is clear in requiring that all derivative works of code under the GPL must themselves be under the GPL". This is a little less strict with the LGPL. But see the above link to the SO post. This is even a considered a problem with javascript that is not linking in that sense. In the end it's for lawyer to decide.

But the bottom line: It's a legal nightmare that many people try to stay clear from. Even projects at the [Apache Software Foundation are not allowed to use libraries under the GPL license](https://www.apache.org/licenses/GPL-compatibility.html).

A little simplified: It's the license you use when you only want GPLed open source projects to use your code.

What some project do is e.g. to dual license. Or switch to a more permissive license.

I guess the question is what you intentions are. Do you actively want to prohibit people from using the library in a non-GPL project?

I am personally in the MIT/BSD/Apache camp. It's where you need to give credit, but it does not restrict the people using my code like the GPL does.

**Comment by Saigesp** [comment]
Thanks for the explanation!

I think I need to find out more. I understand that going from a GPL to an MIT/BSD/Apache  will not be a problem, but I am worried about going back and creating some problems if someone have started using it under MIT.

I would like to make the decision together with more contributors, but at the moment I am alone :confused:

However, if you need an exception I will be happy to provide one.

**Comment by tcurdt** [comment]
If you have any questions I am happy to help with further links or to answer questions (as good as I can).

Indeed going back and forth could be tricky. To avoid this some projects go the dual-licensing route. On the other hand it should be no problem for (L)GPL projects to use MIT/BSD/Apache projects. But maybe have a look at [this discussion about how jQuery](https://softwareengineering.stackexchange.com/questions/139663/confusion-about-dual-license-mit-gpl-javascript-for-use-on-my-website) handles this.

In the end [vue itself also uses the MIT license](https://github.com/vuejs/vue/blob/master/LICENSE).

> I would like to make the decision together with more contributors, but at the moment I am alone 😕

Maybe this will change after a license change :-) But kidding aside:
I think it's a super useful library. It would be a shame if people cannot use it.

> However, if you need an exception I will be happy to provide one.

IANAL so I am not sure how that wold work exactly. But thanks a lot for that offer!
I still think a license change would be the best possible outcome - but it sounds like a good plan B :)

**Comment by Saigesp** [comment]
I have done some research and consulted other people and it seems that the LGPL license is the most appropriate. 

I'm going to find out a little more and if everything is correct I will update the license.

Thanks for the advice!

**Comment by tcurdt** [comment]
Unfortunately I don't think it will be enough for projects e.g. at the ASF. Here is a [link to the discussion](https://issues.apache.org/jira/browse/LEGAL-192). But it is of course much much less problematic than the GPL.

I still hope you reconsider dual licensing (what e.g. jquery uses) but of course I will have to respect your decision as the author. 

Thanks for looking into that!

**Comment by Saigesp** [comment]
From what I have understood, I believe that, given the early stage of development, the LGPL is enough. If the project evolves, I will consider using a dual license.

Thank you for your comments! I am happy to discuss these issues with people with more experience than me :)

**Comment by tcurdt** [comment]
We will discuss internally if we can use it like that.
Thanks for the change!
