### ISSUE TITLE
Dual axes line bar chart

### ISSUE THREAD

**Issue by durga-kale** [Saigesp/vue-d3-charts#33]
Hi,

i am looking for creating dual axes line bar chart using vue-d3-charts. 
Any thoughts on this, would be helpful
<img width="926" alt="dual-axis" src="https://user-images.githubusercontent.com/69461817/118838099-096a9900-b8e3-11eb-947b-c5ed1e27d0b6.png">

**Comment by Saigesp** [comment]
Hi @durga-kale 
This functionality is not planned for the time being. However it is not a complex chart, I recommend you try to do it directly with D3.

Best regards
