### ISSUE TITLE
Line chart lines update does not include new data points

### ISSUE THREAD

**Issue by RichardJong** [Saigesp/vue-d3-charts#9]
When adding data, points are added to the chart but the lines (paths) are not extended to the new points.

**Comment by Saigesp** [comment]
Thanks for reporting! It's now fixed with PR #10 , please update to version 0.2.7

**Comment by Saigesp** [comment]
@RichardJong Ive added an example on [line chart's page](https://saigesp.github.io/vue-d3-charts/#/linechart)

**Comment by Saigesp** [comment]
@RichardJong there's now an example on [line chart's documentation page](https://saigesp.github.io/vue-d3-charts/#/linechart)

**Comment by RichardJong** [comment]
Awesome, thanks for the quick fix!
